/*Copyright (c) 2019 , saberyjs@gmail.com
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
3. All advertising materials mentioning features or use of this software
   must display the following acknowledgement:
   This product includes software developed by the <organization>.
4. Neither the name of the <organization> nor the
   names of its contributors may be used to endorse or promote products
   derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY <COPYRIGHT HOLDER> ''AS IS'' AND ANY
EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
//refer to document https://www.restapitutorial.com/httpstatuscodes.html

#ifndef STL_CLONE_HTTP_CODE_H
#define STL_CLONE_HTTP_CODE_H

#define HTTP_STATUS_CODE_CONTINUE 100
#define HTTP_STATUS_CODE_SWITCH_PROTOCOL 101
#define HTTP_STATUS_CODE_PROCESSING 102

#define HTTP_STATUS_CODE_OK 200
#define HTTP_STATUS_CODE_CREATED 201
#define HTTP_STATUS_CODE_ACCEPTED 202
#define HTTP_STATUS_CODE_NO_AUTHORITATIVE_INFORMATION 203
#define HTTP_STATUS_CODE_NO_CONTENT 204
#define HTTP_STATUS_CODE_RESET_CONTENT 205
#define HTTP_STATUS_CODE_PARTIAL_CONTENT 206
#define HTTP_STATUS_CODE_MULTI_STATUS 207
#define HTTP_STATUS_CODE_ALREADY_REPORTED 208
#define HTTP_STATUS_CODE_MULTI_CHOICES 209


#define HTTP_STATUS_CODE_MOVED_PERMANENTLY 301
#define HTTP_STATUS_CODE_FOUND 302
#define HTTP_STATUS_CODE_SEE_OTHER 303
#define HTTP_STATUS_CODE_NOT_MODIFIED 304
#define HTTP_STATUS_CODE_USE_PROXY 305
#define HTTP_STATUS_CODE_TEMPORARY_REDIRECT 307
#define HTTP_STATUS_CODE_PERMANENT_REDIRECT 308
#define HTTP_STATUS_CODE_BAD_REQUEST 400
#define HTTP_STATUS_CODE_UNAUTHORIZED 401
#define HTTP_STATUS_CODE_PAYMENT_REQUIRED 402
#define HTTP_STATUS_CODE_FORBIDDEN 403
#define HTTP_STATUS_CODE_NOT_FOUND 404
#define HTTP_STATUS_CODE_METHOD_NOT_ALLOWED 405
#define HTTP_STATUS_CODE_NOT_ACCEPTABLE 406
#define HTTP_STATUS_CODE_PROXY_AUTHENTICATION_REQUIRED 407
#define HTTP_STATUS_CODE_REQUEST_TIMEOUT 408
#define HTTP_STATUS_CODE_CONFLICT 409
#define HTTP_STATUS_CODE_GONE 410
#define HTTP_STATUS_CODE_LENGTH_REQUIRED 411
#define HTTP_STATUS_CODE_PRECONDITION_FAILED 412
#define HTTP_STATUS_CODE_REQUEST_ENTITY_TOO_LARGE 413
#define HTTP_STATUS_CODE_REQUEST_URL_TOO_LONG 414
#define HTTP_STATUS_CODE_UNSUPPORTED_MEDIA_TYPE 415
#define HTTP_STATUS_CODE_REQUEST_RANGE_NOT_SATISFIABLE 416
#define HTTP_STATUS_CODE_EXPECTATION_FAILED 417
#define HTTP_STATUS_CODE_TEAPOT 418
#define HTTP_STATUS_CODE_ENHANCE_YOUR_CALM 420
#define HTTP_STATUS_CODE_UNPROCESSABLE_ENTITY 422
#define HTTP_STATUS_CODE_LOCKED 423
#define HTTP_STATUS_CODE_FAILED_DEPENDENCY 424
#define HTTP_STATUS_CODE_UPGRADE_REQUIRED 426
#define HTTP_STATUS_CODE_PRECONDITION_REQUIRED 428
#define HTTP_STATUS_CODE_TOO_MANY_REQUESTS 429
#define HTTP_STATUS_CODE_REQUEST_HEADER_FIELD_TOO_LARGE 431
#define HTTP_STATUS_CODE_NO_RESPONSE 444
#define HTTP_STATUS_CODE_RETRY_WITH 449
#define HTTP_STATUS_CODE_UNAVAILABLE_FOR_LEAGAL_REASON  451
#define HTTP_STATUS_CODE_CLIENT_CLOSED_REQUEST 499


#define HTTP_STATUS_CODE_INTERNAL_SERVER_ERROR 500
#define HTTP_STATUS_CODE_BAD_GATEWAY 502
#define HTTP_STATUS_CODE_SERVIC_UNAVAILABLE 503
#define HTTP_STATUS_CODE_GATEWAY_TIMEOUT  504
#define HTTP_STATUS_CODE_HTTP_VERSION_NOT_SUPPORTED 505
#define HTTP_STATUS_CODE_NETWORK_READ_TIMEOUT_ERROR 598
#define HTTP_STATUS_CODE_NETWORK_CONNECT_TIMEOUT_ERROR 599


#define HTTP_STATUS_CODE_OVERVIEW_CONTINUE  ("Continue")
#define HTTP_STATUS_CODE_OVERVIEW_SWITCH_PROTOCOL ("Switching Protocols")
#define HTTP_STATUS_CODE_OVERVIEW_OK ("Ok")
#define HTTP_STATUS_CODE_OVERVIEW_CREATED ("Created")
#define HTTP_STATUS_CODE_OVERVIEW_ACCEPTED ("Accepted")
#define HTTP_STATUS_CODE_OVERVIEW_NO_AUTHORITATIVE_INFORMATION ("Non-Authoritative Information")
#define HTTP_STATUS_CODE_OVERVIEW_NO_CONTENT ("No Content")
#define HTTP_STATUS_CODE_OVERVIEW_RESET_CONTENT ("Reset Content")
#define HTTP_STATUS_CODE_OVERVIEW_PARTIAL_CONTENT ("Partial Content")
#define HTTP_STATUS_CODE_OVERVIEW_MULTI_CHOICES ("Multiple Choices")
#define HTTP_STATUS_CODE_OVERVIEW_MOVED_PERMANENTLY ("Moved Permanently")
#define HTTP_STATUS_CODE_OVERVIEW_FOUND ("Found")
#define HTTP_STATUS_CODE_OVERVIEW_SEE_OTHER ("See Other")
#define HTTP_STATUS_CODE_OVERVIEW_NOT_MODIFIED ("Not Modified")
#define HTTP_STATUS_CODE_OVERVIEW_USE_PROXY ("Use Proxy")
#define HTTP_STATUS_CODE_OVERVIEW_TEMPORARY_REDIRECT ("Temporary Redirect")
#define HTTP_STATUS_CODE_OVERVIEW_BAD_REQUEST  ("Bad Request")
#define HTTP_STATUS_CODE_OVERVIEW_UNAUTHORIZED ("Unauthorized")
#define HTTP_STATUS_CODE_OVERVIEW_PAYMENT_REQUIRED ("Payment Required")
#define HTTP_STATUS_CODE_OVERVIEW_FORBIDDEN ("Forbidden")
#define HTTP_STATUS_CODE_OVERVIEW_NOT_FOUND ("Not Found")
#define HTTP_STATUS_CODE_OVERVIEW_METHOD_NOT_ALLOWED ("Method Not Allowed")
#define HTTP_STATUS_CODE_OVERVIEW_NOT_ACCEPTABLE ("Not Acceptable")
#define HTTP_STATUS_CODE_OVERVIEW_PROXY_AUTHENTICATION_REQUIRED ("Proxy Authentication Required")
#define HTTP_STATUS_CODE_OVERVIEW_REQUEST_TIMEOUT ("Request Time-out")
#define HTTP_STATUS_CODE_OVERVIEW_CONFLICT ("Conflict")
#define HTTP_STATUS_CODE_OVERVIEW_GONE ("Gone")
#define HTTP_STATUS_CODE_OVERVIEW_LENGTH_REQUIRED ("Length Required")
#define HTTP_STATUS_CODE_OVERVIEW_PRECONDITION_FAILED ("Precondition Failed")
#define HTTP_STATUS_CODE_OVERVIEW_REQUEST_ENTITY_TOO_LARGE ("Request Entity Too Large")
#define HTTP_STATUS_CODE_OVERVIEW_REQUEST_URL_TOO_LONG ("Request-URI Too Large")
#define HTTP_STATUS_CODE_OVERVIEW_UNSUPPORTED_MEDIA_TYPE ("Unsupported Media Type")
#define HTTP_STATUS_CODE_OVERVIEW_REQUEST_RANGE_NOT_SATISFIABLE ("Requested range not satisfiable")
#define HTTP_STATUS_CODE_OVERVIEW_EXPECTATION_FAILED ("Expectation Failed")
#define HTTP_STATUS_CODE_OVERVIEW_INTERNAL_SERVER_ERROR ("Internal Server Error")
#define HTTP_STATUS_CODE_OVERVIEW_NOT_IMPLEMENT ("Not Implemented")
#define HTTP_STATUS_CODE_OVERVIEW_BAD_GATEWAY ("Bad Gateway")
#define HTTP_STATUS_CODE_OVERVIEW_SERVICE_UNAVAILABLE ("Service Unavailable")
#define HTTP_STATUS_CODE_OVERVIEW_GATEWAY_TIMEOUT ("Gateway Time-out")
#define HTTP_STATUS_CODE_OVERVIEW_HTTP_VERSION_UNSUPPORT (" HTTP Version not supported")


#endif //STL_CLONE_HTTP_CODE_H
